name: PR Check

on:
  pull_request:
    branches:
      - master
    path:
      - 'UI/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r UI/requirements.txt

      - name: Lint dependencies
        run: |
          pip install flake8 black isort

      - name: Run flake8
        run: flake8 UI/

      - name: Run black --check
        run: black UI/ --check

      - name: Run isort
        run: isort UI/ --check-only

  security_scan:
      name: Security Scan
      runs-on: ubuntu-latest
      needs: lint

      steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install security tools
          run: |
            pip install bandit safety

        - name: Run Bandit security scan
          run: bandit -r .

        - name: Run Safety vulnerability check
          run: safety check --file=UI/requirements.txt --full-report

